In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv("../data/raw/train_data.csv")

train_df.head()

,train_id,train_name,source,destination,distance_km,scheduled_departure,weather,temperature,rainfall,station_delay,previous_delay,delay_minutes
0,TRN1001,Jan Shatabdi,Guntur,Tirupati,350,10:00,Rain,38,12.48,6.12,15.07,28.32
1,TRN1002,Garib Rath,Hyderabad,Vijayawada,539,21:00,Clear,34,41.98,2.90,4.28,15.53
2,TRN1003,Shatabdi Express,Guntur,Tirupati,646,19:00,Cloudy,20,68.80,2.90,21.39,17.81
3,TRN1004,Krishna Express,Secunderabad,Nizamabad,419,14:00,Cloudy,29,39.61,9.48,13.76,16.29
4,TRN1005,Rajdhani Express,Nellore,Chennai,469,21:00,Cloudy,39,2.51,4.29,16.41,26.34

In [3]:
print("Rows:", train_df.shape[0])
print("Columns:", train_df.shape[1])

Rows: 5000
Columns: 12

In [4]:
train_df.isnull().sum()

train_id               0
train_name             0
source                 0
destination            0
distance_km            0
scheduled_departure    0
weather                0
temperature            0
rainfall               0
station_delay          0
previous_delay         0
delay_minutes          0
dtype: int64

In [5]:
print("Duplicate rows:", train_df.duplicated().sum())

Duplicate rows: 0

In [6]:
train_df = train_df.drop_duplicates()

print("Shape after removing duplicates:", train_df.shape)

Shape after removing duplicates: (5000, 12)

In [7]:
train_df.dtypes

train_id                   str
train_name                 str
source                     str
destination                str
distance_km              int64
scheduled_departure        str
weather                    str
temperature              int64
rainfall               float64
station_delay          float64
previous_delay         float64
delay_minutes          float64
dtype: object

In [8]:
train_df["departure_hour"] = pd.to_datetime(
    train_df["scheduled_departure"],
    format="%H:%M"
).dt.hour

In [9]:
train_df[["scheduled_departure", "departure_hour"]].head()

  scheduled_departure  departure_hour
0               10:00              10
1               21:00              21
2               19:00              19
3               14:00              14
4               21:00              21

In [10]:
train_df = train_df.drop(
    columns=["scheduled_departure"]
)

In [11]:
train_df[[
    "distance_km",
    "temperature",
    "rainfall",
    "station_delay",
    "previous_delay",
    "delay_minutes"
]].describe()

,distance_km,temperature,rainfall,station_delay,previous_delay,delay_minutes
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,388.976600,29.552800,39.973776,5.188808,8.523648,18.520758
std,179.401661,6.880922,23.032511,3.633915,6.257838,8.364112
min,80.000000,18.000000,0.010000,0.000000,0.000000,0.000000
25%,235.000000,24.000000,20.207500,2.307500,3.410000,12.607500
50%,386.000000,29.000000,40.055000,5.010000,8.115000,18.070000
75%,546.250000,36.000000,59.330000,7.690000,12.742500,23.957500
max,699.000000,41.000000,79.950000,18.640000,35.320000,50.210000

In [12]:
numeric_columns = [
    "distance_km",
    "temperature",
    "rainfall",
    "station_delay",
    "previous_delay",
    "delay_minutes"
]

for column in numeric_columns:
    print(
        column,
        "negative values:",
        (train_df[column] < 0).sum()
    )

distance_km negative values: 0
temperature negative values: 0
rainfall negative values: 0
station_delay negative values: 0
previous_delay negative values: 0
delay_minutes negative values: 0

In [13]:
print(train_df.info())
print("\nMissing values:")
print(train_df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   train_id        5000 non-null   str
 1   train_name      5000 non-null   str
 2   source          5000 non-null   str
 3   destination     5000 non-null   str
 4   distance_km     5000 non-null   int64
 5   weather         5000 non-null   str
 6   temperature     5000 non-null   int64
 7   rainfall        5000 non-null   float64
 8   station_delay   5000 non-null   float64
 9   previous_delay  5000 non-null   float64
 10  delay_minutes   5000 non-null   float64
 11  departure_hour  5000 non-null   int32
dtypes: float64(4), int32(1), int64(2), str(5)
memory usage: 666.5 KB
None

Missing values:
train_id          0
train_name        0
source            0
destination       0
distance_km       0
weather           0
temperature       0
rainfall          0
station_delay     0
previous_delay    0
delay_minutes     0
departure_hour    0
dtype: int64

In [14]:
train_df.to_csv(
    "../data/processed/delay_processed.csv",
    index=False
)

print("Train delay dataset cleaned and saved successfully!")

Train delay dataset cleaned and saved successfully!

In [15]:
passenger_df = pd.read_csv(
    "../data/raw/passenger_data.csv"
)

passenger_df.head()

,date,station,train_id,hour,day_of_week,holiday,weather,special_event,passenger_count
0,2025-05-20,Visakhapatnam,TRN1500,21,1,0,Clear,0,571
1,2025-06-19,Tirupati,TRN1758,20,3,0,Rain,1,1047
2,2025-11-21,Visakhapatnam,TRN4588,9,4,0,Clear,0,661
3,2025-02-10,Secunderabad,TRN1684,0,0,0,Cloudy,0,313
4,2025-11-28,Guntur,TRN4985,23,4,0,Clear,0,268

In [16]:
print("Shape:", passenger_df.shape)

print("\nMissing values:")
print(passenger_df.isnull().sum())

print("\nDuplicates:")
print(passenger_df.duplicated().sum())

Shape: (5000, 9)

Missing values:
date               0
station            0
train_id           0
hour               0
day_of_week        0
holiday            0
weather            0
special_event      0
passenger_count    0
dtype: int64

Duplicates:
0

In [17]:
passenger_df["date"] = pd.to_datetime(
    passenger_df["date"]
)

In [18]:
passenger_df = passenger_df.drop_duplicates()

In [19]:
passenger_df.describe()

,date,hour,day_of_week,holiday,special_event,passenger_count
count,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2025-07-02 04:05:22.560000,11.476800,3.020200,0.098400,0.075600,504.853600
min,2025-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,64.000000
25%,2025-04-04 00:00:00,5.750000,1.000000,0.000000,0.000000,353.000000
50%,2025-06-30 00:00:00,11.000000,3.000000,0.000000,0.000000,491.500000
75%,2025-09-30 00:00:00,17.000000,5.000000,0.000000,0.000000,627.000000
max,2025-12-31 00:00:00,23.000000,6.000000,1.000000,1.000000,1324.000000
std,NaN,6.906099,2.003945,0.297885,0.264383,193.351341

In [20]:
passenger_df.to_csv(
    "../data/processed/passenger_processed.csv",
    index=False
)

print("Passenger dataset cleaned and saved!")

Passenger dataset cleaned and saved!

In [21]:
maintenance_df = pd.read_csv(
    "../data/raw/maintenance_data.csv"
)

maintenance_df.head()

,train_id,engine_temperature,brake_pressure,vibration,wheel_condition,engine_hours,last_service_days,maintenance_count,failure
0,TRN5021,91.33,88.74,3.28,55,6057,67,7,0
1,TRN4020,75.91,93.46,3.34,75,5416,257,11,0
2,TRN5714,87.09,90.08,5.38,96,5831,229,4,0
3,TRN5915,62.02,91.54,4.60,85,4060,137,14,1
4,TRN3186,91.01,87.05,3.15,57,11743,146,9,0

In [22]:
print("Shape:", maintenance_df.shape)

print("\nMissing values:")
print(maintenance_df.isnull().sum())

print("\nDuplicates:")
print(maintenance_df.duplicated().sum())

Shape: (5000, 9)

Missing values:
train_id              0
engine_temperature    0
brake_pressure        0
vibration             0
wheel_condition       0
engine_hours          0
last_service_days     0
maintenance_count     0
failure               0
dtype: int64

Duplicates:
0

In [23]:
maintenance_df = maintenance_df.drop_duplicates()

In [24]:
maintenance_df.describe()

,engine_temperature,brake_pressure,vibration,wheel_condition,engine_hours,last_service_days,maintenance_count,failure
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,84.973708,94.886372,3.949630,75.121000,8008.815200,181.124200,6.976400,0.302400
std,12.084750,8.052807,1.492847,14.610032,4053.995083,104.100823,4.329526,0.459343
min,40.370000,65.660000,-1.730000,50.000000,1003.000000,1.000000,0.000000,0.000000
25%,76.930000,89.527500,2.920000,63.000000,4471.250000,89.000000,3.000000,0.000000
50%,85.035000,94.850000,3.970000,75.000000,8022.500000,180.000000,7.000000,0.000000
75%,93.070000,100.100000,4.950000,88.000000,11513.250000,272.000000,11.000000,1.000000
max,129.330000,122.840000,8.430000,100.000000,14999.000000,364.000000,14.000000,1.000000

In [25]:
maintenance_df.describe()

,engine_temperature,brake_pressure,vibration,wheel_condition,engine_hours,last_service_days,maintenance_count,failure
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,84.973708,94.886372,3.949630,75.121000,8008.815200,181.124200,6.976400,0.302400
std,12.084750,8.052807,1.492847,14.610032,4053.995083,104.100823,4.329526,0.459343
min,40.370000,65.660000,-1.730000,50.000000,1003.000000,1.000000,0.000000,0.000000
25%,76.930000,89.527500,2.920000,63.000000,4471.250000,89.000000,3.000000,0.000000
50%,85.035000,94.850000,3.970000,75.000000,8022.500000,180.000000,7.000000,0.000000
75%,93.070000,100.100000,4.950000,88.000000,11513.250000,272.000000,11.000000,1.000000
max,129.330000,122.840000,8.430000,100.000000,14999.000000,364.000000,14.000000,1.000000

In [26]:
print(
    maintenance_df["failure"].value_counts()
)

failure
0    3488
1    1512
Name: count, dtype: int64

In [27]:
maintenance_df.to_csv(
    "../data/processed/maintenance_processed.csv",
    index=False
)

print("Maintenance dataset cleaned and saved!")

Maintenance dataset cleaned and saved!

In [28]:
crowd_df = pd.read_csv(
    "../data/raw/station_crowd.csv"
)

crowd_df.head()

,date,station,hour,day_of_week,holiday,train_frequency,passenger_count,entry_count,exit_count,crowd_level
0,2025-04-15,Kurnool,9,1,0,3,139,106,31,Low
1,2025-06-30,Tirupati,2,0,0,8,667,386,394,Low
2,2025-02-15,Nellore,0,5,0,7,1312,723,664,Medium
3,2025-10-14,Vijayawada,15,1,0,12,1390,1045,461,Medium
4,2025-09-19,Warangal,9,4,0,4,975,395,209,Medium

In [29]:
print("Shape:", crowd_df.shape)

print("\nMissing values:")
print(crowd_df.isnull().sum())

print("\nDuplicates:")
print(crowd_df.duplicated().sum())

Shape: (5000, 10)

Missing values:
date               0
station            0
hour               0
day_of_week        0
holiday            0
train_frequency    0
passenger_count    0
entry_count        0
exit_count         0
crowd_level        0
dtype: int64

Duplicates:
0

In [30]:
crowd_df["date"] = pd.to_datetime(
    crowd_df["date"]
)

In [31]:
crowd_df = crowd_df.drop_duplicates()

In [32]:
print(
    crowd_df["crowd_level"].value_counts()
)

crowd_level
Medium    2658
Low       1202
High      1140
Name: count, dtype: int64

In [33]:
crowd_df.to_csv(
    "../data/processed/crowd_processed.csv",
    index=False
)

print("Station crowd dataset cleaned and saved!")

Station crowd dataset cleaned and saved!

In [34]:
import os

processed_files = os.listdir("../data/processed")

print("Processed datasets:")
for file in processed_files:
    print("✓", file)

Processed datasets:
✓ crowd_processed.csv
✓ delay_processed.csv
✓ maintenance_processed.csv
✓ passenger_processed.csv